spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/jobapplication
    username: root
    password: root
    driverClassName: org.postgresql.Driver
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
   
info:
  app: 
    name: jobApplication
    description: build by suraj
    version: 1.0.0
    
 
    

